package appchamada;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(){
        initComponents();
    }
    
    public TelaPrincipal(Object nomeCurso, Object nomeTurma,ArrayList<Aluno> dados) {
        initComponents();
        txtCurso.setText(nomeCurso.toString());
        txtTurma.setText(nomeTurma.toString());
        //Data atual
        Date data = new Date();
    
        //String que armazena a data atual
        String dataAtual;
        dataAtual = java.text.DateFormat.getDateInstance(DateFormat.MEDIUM).format(data);
    
        //Titulo das colunas da tabela
        String[] titulo = new String[3];
        titulo[0]="MATRICULA";
        titulo[1]="NOME";
        titulo[2]=dataAtual;
        
        //Dados dos alunos convertidos para a tabela
        Object[][] dadosChamada = new Object[dados.size()][3];
        
        int i, j;
        for(i=0; i<dados.size(); i++){
            for(j=0; j<3; j++){
                if(j==0){
                    dadosChamada[i][j] = dados.get(i).getMatricula();
                }
                else if(j==1){
                    dadosChamada[i][j] = dados.get(i).getNome();
                }
                else
                {
                    dadosChamada[i][j] = dados.get(i).isStatus();
                }
            }
        }
        
        TabelaDaChamada2 tblChamada = new TabelaDaChamada2(dadosChamada, titulo);
        tblInserida.setModel(tblChamada);
        tblInserida.setFont(new Font("Monospaced", Font.PLAIN, 15));
        MyCellRendererOutrosValores renderer = new MyCellRendererOutrosValores(Color.CYAN, Color.ORANGE);
        tblInserida.setDefaultRenderer(String.class, renderer);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        this.setSize((int) d.getWidth(), d.height-40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInserida = new javax.swing.JTable();
        txtCurso = new javax.swing.JLabel();
        txtTurma = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(793, 511));

        tblInserida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblInserida.setGridColor(new java.awt.Color(0, 0, 0));
        tblInserida.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tblInserida.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tblInserida);

        txtCurso.setBackground(new java.awt.Color(255, 255, 102));
        txtCurso.setFont(txtCurso.getFont().deriveFont(txtCurso.getFont().getStyle() | java.awt.Font.BOLD, txtCurso.getFont().getSize()+7));
        txtCurso.setText("Curso");

        txtTurma.setBackground(new java.awt.Color(255, 255, 51));
        txtTurma.setFont(txtTurma.getFont().deriveFont(txtTurma.getFont().getStyle() | java.awt.Font.BOLD, txtTurma.getFont().getSize()+7));
        txtTurma.setText("Turma");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(552, 552, 552))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addGap(45, 45, 45)))
        );

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appchamada/001-plus.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appchamada/002-x-button.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(507, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(btnCancelar)
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 606, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCancelar)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        TelaInicial.retornar();
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Cria Lista de Alunos
        ArrayList<Aluno> saveARQ = new ArrayList<Aluno>();
        Aluno[] recebido = new Aluno[this.tblInserida.getRowCount()];
        Object dadosTabela;
        int i, j;
        
        for(i=0; i<this.tblInserida.getRowCount(); i++){
            recebido[i] = new Aluno();
        }
        
        for(i=0; i<this.tblInserida.getRowCount(); i++){
            for(j=0; j<3; j++){
                dadosTabela = this.tblInserida.getValueAt(i,j);
                switch (j) {
                    case 0:
                        recebido[i].setMatricula(dadosTabela.toString());
                        break;
                    case 1:
                        recebido[i].setNome(dadosTabela.toString());
                        break;
                    case 2:
                        if(dadosTabela.toString()=="true"){
                            recebido[i].setStatus(true);
                        }
                        else
                        {
                            recebido[i].setStatus(false);
                        }
                }
            }
        }
        for(i=0; i<this.tblInserida.getRowCount(); i++){
            saveARQ.add(i, recebido[i]);
        }
        
        int res=0;
        
        //Data atual
        Date data = new Date();
    
        //String que armazena a data atual
        String dataAtual;
        String data2;
        
        data2 = java.text.DateFormat.getDateInstance(DateFormat.MEDIUM).format(data);
        dataAtual = java.text.DateFormat.getDateInstance(DateFormat.LONG).format(data);
        try {
            CrunchifyCSVtoArrayList salvo = new CrunchifyCSVtoArrayList();
            res = salvo.salvarArquivo(saveARQ, dataAtual, this.txtCurso.getText(), this.txtTurma.getText(), data2);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(res==1)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblInserida;
    private javax.swing.JLabel txtCurso;
    private javax.swing.JLabel txtTurma;
    // End of variables declaration//GEN-END:variables
}
